FROM python:3.9-slim
WORKDIR /api

COPY ./example_flask/app.py ./example_flask/requirements.txt ./example_flask/boot.sh ./example_flask/wsgi.py ./

RUN pip install -r ./requirements.txt
ENV FLASK_DEBUG=1 FLASK_ENV=development FLASK_APP=app.py

RUN chmod +x boot.sh

EXPOSE 5000

# ENTRYPOINT [ "./boot.sh" ]
